inherit_from: base_rubocop.yml

AllCops:
  NewCops: disable
  TargetRubyVersion: 2.7.1

Style/FileName:
  Exclude:
    - 'bin/codeclimate-standard'

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false
